#!/usr/bin/php -dmemory_limit=128M
<?
define('DS', DIRECTORY_SEPARATOR);
define('BW', true);
define('BW_PATH', dirname(__FILE__));
define('BW_PATH_CONFIG', BW_PATH .DS. 'config.php');

//print "memory_limit=".ini_get("memory_limit")."\n";
//print "safe_mode=".ini_get("safe_mode")."\n";

$command = @$argv[1];
switch($command)
{
    case 'install':
        require('libraries/core/install.php');
        $i = new bwInstall($argv);
        break;

    default:
        echo <<<EOF

Lista de comando disponíves:

  install - Instala e atualiza sistema, componentes, módulos e plugins
            Para mais informações, use: bw install --help


EOF;
break;
}
?>
