#!/usr/bin/php -dmemory_limit=128M
<?php

require 'inc/init.php';

function update($com)
{
    // ignore componentes padrões
    if(preg_match('#^php$|^sistema$|^usuarios$#', $com))
        return false;
    
    $pasta = sprintf('../components/%s', $com);

    if (!is_dir($pasta)) {
        echo sprintf("Componente %s não instalado!\n", $com);
        return false;
    }

    echo sprintf("Atualizando componente '%s'\n", $com);
    $command = sprintf('cd %s;git pull origin master', $pasta);

    system($command, $retorno);
}

if (isset($argv[1])) {

    if ($argv[1] == '--all') {

        $componentes = bwFolder::listarConteudo(BW_PATH_COMPONENTS, false, true, false, false);
        sort($componentes);

        foreach ($componentes as $com) {
            update($com);
        }
    } else {
        update($argv[1]);
    }
} else {
    echo "Nenhum componente foi selecionado!\n";
}
